name: Update Master

on: 
  pull_request_target:
    types:
      - closed
    branches: 
      - 'development'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: echo "âœ… Checking out development."
    - name: checkout
      uses: actions/checkout@v3
    - run: echo "ðŸŽ¯ Merging development into master."  
    - name: merge
      uses: everlytic/branch-merge@1.1.2
    - run: echo "ðŸ¥ƒ Workflow complete." 